import type { Place } from "../../types";

export const TUTU_PLACES: Place[] = [
  {
    id: "tutu_home",
    name: "图图家",
    kind: "home",
    rect: { x: 1, y: 1, w: 6, h: 6 },
    anchor: { x: 4, y: 6 },
    color: "#ffd9b3",
    emoji: "🏠",
  },
  {
    id: "niu_home",
    name: "牛爷爷家",
    kind: "home",
    rect: { x: 8, y: 1, w: 5, h: 6 },
    anchor: { x: 10, y: 6 },
    color: "#e6c9a8",
    emoji: "🏡",
  },
  {
    id: "park",
    name: "翻斗公园",
    kind: "park",
    rect: { x: 14, y: 1, w: 8, h: 8 },
    anchor: { x: 17, y: 8 },
    color: "#bfe5a0",
    emoji: "🌳",
  },
  {
    id: "kindergarten",
    name: "翻斗幼儿园",
    kind: "kindergarten",
    rect: { x: 23, y: 1, w: 8, h: 7 },
    anchor: { x: 27, y: 7 },
    color: "#ffe17a",
    emoji: "🏫",
  },
  {
    id: "noodle_shop",
    name: "面馆",
    kind: "restaurant",
    rect: { x: 1, y: 12, w: 7, h: 6 },
    anchor: { x: 4, y: 12 },
    color: "#ffb3b3",
    emoji: "🍜",
  },
  {
    id: "convenience",
    name: "便利店",
    kind: "shop",
    rect: { x: 10, y: 12, w: 6, h: 5 },
    anchor: { x: 12, y: 12 },
    color: "#cfb3ff",
    emoji: "🏪",
  },
  {
    id: "plaza",
    name: "街心广场",
    kind: "plaza",
    rect: { x: 18, y: 11, w: 13, h: 7 },
    anchor: { x: 24, y: 14 },
    color: "#a8dadc",
    emoji: "⛲",
  },
];
