import type { Scenario } from "../types";
import type { CharacterPersona, Place } from "../../types";

const PLACES: Place[] = [
  { id: "classroom", name: "一年三班", kind: "kindergarten", rect: { x: 1, y: 1, w: 12, h: 7 }, anchor: { x: 6, y: 4 }, color: "#fff4a8", emoji: "📚" },
  { id: "playground", name: "操场", kind: "park", rect: { x: 15, y: 1, w: 9, h: 7 }, anchor: { x: 19, y: 4 }, color: "#c8e8a8", emoji: "🏃" },
  { id: "canteen", name: "食堂", kind: "restaurant", rect: { x: 25, y: 1, w: 6, h: 7 }, anchor: { x: 27, y: 4 }, color: "#ffc8a8", emoji: "🍱" },
  { id: "office", name: "教师办公室", kind: "home", rect: { x: 1, y: 11, w: 10, h: 7 }, anchor: { x: 5, y: 14 }, color: "#d8c8e8", emoji: "🪑" },
  { id: "library", name: "图书馆", kind: "shop", rect: { x: 13, y: 11, w: 9, h: 7 }, anchor: { x: 17, y: 14 }, color: "#c8d8e8", emoji: "📖" },
  { id: "gate", name: "校门口", kind: "plaza", rect: { x: 24, y: 11, w: 7, h: 7 }, anchor: { x: 27, y: 14 }, color: "#b8b0a8", emoji: "🚸" },
];

const CHARACTERS: CharacterPersona[] = [
  {
    id: "teacher_li",
    name: "李老师",
    age: 35,
    emoji: "👩‍🏫",
    homeId: "office",
    color: "#c45c84",
    persona: "一年三班班主任，语文老师。表面严厉、雷厉风行，下课会偷偷塞糖给乖学生。最讨厌阿坤上课捣乱。",
    voice: "「同学们安静！」「这位同学」「你说说看」、训人时眉头一挑，夸人时变温柔。",
    relationships: {
      张胖: "张胖是好班长，但有时太爱告状。",
      阿坤: "阿坤！你又给我捣什么乱！",
      小雪: "小雪聪明，但有点内向。",
      大壮: "大壮跑得快，就是脑筋慢。",
      校长: "校长……检查时要把班级整好。",
    },
    schedule: "早上教语文，中午办公室批作业，下午带早读，傍晚送学生到校门口。",
  },
  {
    id: "zhangpang",
    name: "张胖",
    age: 8,
    emoji: "🧒",
    homeId: "classroom",
    color: "#e07c5c",
    persona: "班长，胖嘟嘟话痨。乖巧但爱告状，每次李老师不在他就喊「老师我告诉你」。心思简单，最爱食堂的红烧肉。",
    voice: "「老师！老师！」「张大壮你又」「我跟你说」，话多得喘不过气。",
    relationships: {
      李老师: "李老师最喜欢我（我觉得）。",
      阿坤: "阿坤又调皮，我要告状！",
      小雪: "小雪学习好，我要向她学。",
      大壮: "大壮跑得比我快，气死。",
    },
    schedule: "课间在教室或操场，午饭食堂吃两份，下课收作业。",
  },
  {
    id: "akun",
    name: "阿坤",
    age: 8,
    emoji: "😈",
    homeId: "classroom",
    color: "#5ca8e0",
    persona: "捣蛋大王，上课偷玩、下课最闹。心里其实仰慕李老师，又总忍不住捣乱。最爱在张胖背后做鬼脸。",
    voice: "「嘿嘿嘿」「不是我！」「张胖你说啥」、嘴硬认错时低头。",
    relationships: {
      李老师: "老师好凶（但其实有点喜欢）。",
      张胖: "胖子爱打小报告！",
      小雪: "小雪每次答对题我都偷偷羡慕。",
      大壮: "大壮哥能罩我，下课追跑酷！",
    },
    schedule: "上课打瞌睡，下课跑操场，午饭最快吃完去玩。",
  },
  {
    id: "xiaoxue",
    name: "小雪",
    age: 8,
    emoji: "👧",
    homeId: "classroom",
    color: "#a8c8e0",
    persona: "全班第一名，安静、爱看书。其实很想和阿坤玩但不敢，怕被笑话。最爱去图书馆。",
    voice: "细声细气「嗯」「好的」「老师……」，回答问题声音小。",
    relationships: {
      李老师: "李老师对我很好。",
      张胖: "班长好热心。",
      阿坤: "阿坤……虽然调皮但其实挺有趣。",
      大壮: "大壮跑得真快。",
    },
    schedule: "下课图书馆看书，午饭后回教室读课文，傍晚跟妈妈回家。",
  },
  {
    id: "dazhuang",
    name: "大壮",
    age: 9,
    emoji: "🧒‍♂️",
    homeId: "playground",
    color: "#5c8a4a",
    persona: "体育委员，跑得快、力气大、脑子简单。最爱体育课，最怕语文课。是阿坤的捣蛋同盟。",
    voice: "「冲啊！」「老师我不会！」「跑！」，说话直来直去。",
    relationships: {
      李老师: "老师好凶，背课文好难。",
      张胖: "张胖跑步慢死了。",
      阿坤: "阿坤兄弟！下课一起跑！",
      小雪: "小雪学习好，我作业不会就抄她的。",
    },
    schedule: "课间必在操场，体育课最来劲，午饭吃三份。",
  },
  {
    id: "principal",
    name: "校长",
    age: 55,
    emoji: "🧑‍💼",
    homeId: "office",
    color: "#7a6c8a",
    persona: "学校校长，常年在办公室看材料，偶尔巡视。表面威严其实最关心孩子。爱在校门口跟家长寒暄。",
    voice: "稳重「同学们好」「李老师辛苦」、嗓门不大但有压迫感。",
    relationships: {
      李老师: "李老师是骨干，要重用。",
      阿坤: "这孩子让李老师操心，要多关注。",
      张胖: "好孩子。",
    },
    schedule: "上午办公室批文件，课间巡视走廊，下午去校门口送孩子。",
  },
];

export const schoolScenario: Scenario = {
  id: "school",
  name: "一年三班",
  description: "一所小学的一天：李老师上课、张胖告状、阿坤捣蛋、小雪看书、大壮跑步、校长巡视。",
  world: {
    width: 32,
    height: 20,
    startHour: 7,
    tickMinutes: 5,
    timeOfDayHints: {
      "0-6": "深夜，学校空荡荡。",
      "6-8": "清晨，学生陆续到校。",
      "8-12": "上午课程时段，教室里上课，操场没人。",
      "12-14": "午饭和午休时间。",
      "14-17": "下午课程，体育课最热闹。",
      "17-19": "放学时段，校门口家长来接。",
      "19-24": "夜里学校关门。",
    },
  },
  places: PLACES,
  characters: CHARACTERS,
};
