import type { Scenario } from "../types";
import type { CharacterPersona, Place } from "../../types";

const PLACES: Place[] = [
  { id: "main_stage", name: "主舞台", kind: "plaza", rect: { x: 1, y: 1, w: 15, h: 9 }, anchor: { x: 8, y: 5 }, color: "#a878e0", emoji: "🎸" },
  { id: "side_stage", name: "副舞台", kind: "plaza", rect: { x: 18, y: 1, w: 13, h: 9 }, anchor: { x: 24, y: 5 }, color: "#e87878", emoji: "🎹" },
  { id: "food_trucks", name: "餐车区", kind: "restaurant", rect: { x: 1, y: 11, w: 12, h: 7 }, anchor: { x: 6, y: 14 }, color: "#ffc878", emoji: "🌭" },
  { id: "lawn", name: "休息草坪", kind: "park", rect: { x: 15, y: 11, w: 9, h: 7 }, anchor: { x: 19, y: 14 }, color: "#98e078", emoji: "🌿" },
  { id: "stalls", name: "周边摊位", kind: "shop", rect: { x: 25, y: 11, w: 6, h: 7 }, anchor: { x: 27, y: 14 }, color: "#78c8e0", emoji: "🎪" },
];

const CHARACTERS: CharacterPersona[] = [
  {
    id: "ale",
    name: "阿乐",
    age: 24,
    emoji: "🤘",
    homeId: "main_stage",
    color: "#7a3ca8",
    persona: "重金属铁粉，每场音乐节必来。穿黑 T 戴皮手套，看到喜欢的乐队就全力 pogo。看不起爱拍照的网红。",
    voice: "「卧槽这段牛逼」「兄弟来一起」、说话夹脏字、激动时声音破音。",
    relationships: {
      Lily: "又是网红来打卡，听不懂还来挤位置。",
      老炮: "前辈！懂的都懂。",
      小新: "新人嘛，慢慢就懂了。",
      摊主大叔: "大叔的热狗便宜量大。",
    },
    schedule: "全程蹲主舞台前排，饿了快速啃个热狗回来。",
  },
  {
    id: "lily",
    name: "Lily",
    age: 22,
    emoji: "💃",
    homeId: "side_stage",
    color: "#ff5c9c",
    persona: "穿搭浮夸的网红，来音乐节主要是拍 vlog。其实不太懂乐队，跟着哼歌词。爱发朋友圈打卡每个摊位。",
    voice: "「家人们」「美哭了」「这个角度」、爱用流行词、说话甜。",
    relationships: {
      阿乐: "这哥们儿盯我看，怪不舒服的。",
      DJ_Mike: "Mike 哥技术好帅，能合作吗。",
      摊主大叔: "热狗摊位挺出片！",
    },
    schedule: "在副舞台和周边摊位之间转，每个角落都打卡。",
  },
  {
    id: "laopao",
    name: "老炮",
    age: 48,
    emoji: "🧔",
    homeId: "lawn",
    color: "#5a4a3a",
    persona: "70 后摇滚老粉，第一届音乐节就来。话不多但每个乐队都熟，能讲他们 20 年前的故事。最看不上现在的电子。",
    voice: "「年轻人」「想当年」「这首啊……」、慢悠悠、聊起音乐眼睛发亮。",
    relationships: {
      阿乐: "这小子有点意思，懂行。",
      Lily: "网红嘛，让人家玩。",
      DJ_Mike: "电子玩意儿……不评论。",
      摊主大叔: "老哥啤酒来一瓶。",
    },
    schedule: "全程坐在休息草坪，抽烟喝啤酒，听喜欢的乐队才起身。",
  },
  {
    id: "xiaoxin",
    name: "小新",
    age: 19,
    emoji: "🧑",
    homeId: "stalls",
    color: "#5ca8c4",
    persona: "第一次来音乐节的菜鸟，朋友放鸽子只能一个人逛。激动又不知所措，看到啥都新鲜。",
    voice: "「哇」「啊真的吗」「不好意思」、说话带点紧张。",
    relationships: {
      阿乐: "那哥们好厉害！",
      Lily: "Lily 姐姐好漂亮！",
      老炮: "大叔好有故事感。",
      摊主大叔: "热狗是真的好吃。",
    },
    schedule: "全场乱逛，哪里热闹去哪里，最后估计累瘫在草坪。",
  },
  {
    id: "hotdog_uncle",
    name: "热狗大叔",
    age: 50,
    emoji: "🧑‍🍳",
    homeId: "food_trucks",
    color: "#c47c3a",
    persona: "餐车老板，热狗摊主。嗓门大、手脚快、人精。每个音乐节都来摆摊，啥怪人都见过。最讨厌付款时砍价的。",
    voice: "嗓门大「热狗烤肠！」「老板来一份！」「现做！」、跟熟客时唠两句。",
    relationships: {
      阿乐: "这哥们儿是回头客。",
      Lily: "这小姑娘只拍不买。",
      老炮: "老哥每年都来。",
      小新: "新面孔，看着挺善良。",
      DJ_Mike: "Mike 哥下了台来吃热狗。",
    },
    schedule: "全程在餐车区忙活，没时间看演出。",
  },
  {
    id: "dj_mike",
    name: "DJ Mike",
    age: 30,
    emoji: "🎧",
    homeId: "side_stage",
    color: "#3a4ac4",
    persona: "副舞台 DJ，间隙打碟暖场。专业、酷、话少。其实社恐，下台后宁愿一个人坐草坪。",
    voice: "「Yo」「OK」「这段 drop」、英文夹中文，下台后变安静。",
    relationships: {
      Lily: "粉丝多，但合作要看公司安排。",
      老炮: "前辈，不知道他听不听电子。",
      阿乐: "金属粉看我估计不爽。",
      摊主大叔: "下台来一份热狗。",
    },
    schedule: "副舞台打碟，间隙到休息草坪躲清静，饿了去餐车区。",
  },
];

export const festivalScenario: Scenario = {
  id: "festival",
  name: "夏日音乐节",
  description: "一场城市音乐节的下午到深夜：摇滚老粉、网红、新人、DJ、餐车老板在草坪上交集。",
  world: {
    width: 32,
    height: 20,
    startHour: 14,
    tickMinutes: 5,
    timeOfDayHints: {
      "0-3": "凌晨，音乐节散场，舞台冷清。",
      "3-13": "音乐节关门时段，没人在场。",
      "13-15": "下午开门，人陆续入场。",
      "15-18": "热场时段，副舞台开始打碟。",
      "18-22": "黄金时段，主舞台压轴乐队登场，人山人海。",
      "22-24": "深夜，收尾乐队，气氛达到顶峰。",
    },
  },
  places: PLACES,
  characters: CHARACTERS,
};
