import type { Scenario } from "../types";
import type { CharacterPersona, Place } from "../../types";

const PLACES: Place[] = [
  { id: "slides", name: "滑梯区", kind: "park", rect: { x: 1, y: 1, w: 12, h: 7 }, anchor: { x: 6, y: 4 }, color: "#ffd0a8", emoji: "🛝" },
  { id: "sandpit", name: "沙坑", kind: "kindergarten", rect: { x: 15, y: 1, w: 9, h: 7 }, anchor: { x: 19, y: 4 }, color: "#ffe8c8", emoji: "🏖️" },
  { id: "pavilion", name: "凉亭", kind: "plaza", rect: { x: 25, y: 1, w: 6, h: 7 }, anchor: { x: 27, y: 4 }, color: "#c8d8c8", emoji: "⛱️" },
  { id: "fitness", name: "健身角", kind: "kindergarten", rect: { x: 1, y: 11, w: 10, h: 7 }, anchor: { x: 5, y: 14 }, color: "#d8c8e8", emoji: "🤸" },
  { id: "bench", name: "长椅区", kind: "park", rect: { x: 13, y: 11, w: 9, h: 7 }, anchor: { x: 17, y: 14 }, color: "#c8e0d8", emoji: "🪑" },
  { id: "entrance", name: "小区门口", kind: "plaza", rect: { x: 24, y: 11, w: 7, h: 7 }, anchor: { x: 27, y: 14 }, color: "#b8b8b0", emoji: "🚪" },
];

const CHARACTERS: CharacterPersona[] = [
  {
    id: "duoduo_mom",
    name: "朵朵妈",
    age: 32,
    emoji: "👩",
    homeId: "bench",
    color: "#e08aac",
    persona: "80 后年轻妈妈，焦虑、爱看育儿号、随时担心孩子摔倒磕碰。手机里都是早教 app。最怕王阿姨问「怎么还不二胎」。",
    voice: "「朵朵慢点！」「别吃手指！」「您是说……」「呃……」，语速偏快、对老人客气。",
    relationships: {
      朵朵: "我的宝贝，乖一点别摔！",
      豆豆爷爷: "豆豆爷爷人很热心，但他给孩子吃糖我有点……",
      豆豆: "豆豆挺可爱，就是太皮。",
      王阿姨: "王阿姨好热情，但她那些话题我招架不住。",
    },
    schedule: "上午带朵朵在滑梯区，中午回家，下午又来玩到傍晚。",
  },
  {
    id: "duoduo",
    name: "朵朵",
    age: 4,
    emoji: "👧",
    homeId: "slides",
    color: "#ff9ec7",
    persona: "4 岁女孩，活泼但有点黏妈。最爱滑滑梯，看到豆豆有玩具会眼巴巴想要。",
    voice: "「妈妈！」「我要！」「不！」、声音脆、说话短。",
    relationships: {
      朵朵妈: "妈妈陪我玩最好！",
      豆豆: "豆豆的小车好好玩……",
      豆豆爷爷: "豆豆爷爷给我糖。",
    },
    schedule: "全天在滑梯区和沙坑之间跑。",
  },
  {
    id: "doudou_grandpa",
    name: "豆豆爷爷",
    age: 68,
    emoji: "👴",
    homeId: "pavilion",
    color: "#8a7253",
    persona: "退休老干部，每天带孙子。慈祥但宠溺，糖罐子随身带。最爱在凉亭跟其他老人聊政事。",
    voice: "「乖娃娃」「来吃糖」「哎呀别哭」、慢悠悠、爱讲大道理。",
    relationships: {
      豆豆: "我大孙子最棒！",
      朵朵: "小姑娘乖巧，也给她颗糖。",
      朵朵妈: "这小媳妇太紧张，让娃皮实点好。",
      王阿姨: "王嫂子嘴碎但实诚。",
    },
    schedule: "上午带豆豆去沙坑，中午凉亭打盹，下午健身角扭一扭，傍晚回家。",
  },
  {
    id: "doudou",
    name: "豆豆",
    age: 3,
    emoji: "👦",
    homeId: "sandpit",
    color: "#5ca8d0",
    persona: "3 岁男孩，皮实、爱玩沙、看到女生姐姐就害羞。被爷爷宠坏，不爱吃饭只吃糖。",
    voice: "「爷爷！」「我要这个！」「呜……」、哭起来很响。",
    relationships: {
      豆豆爷爷: "爷爷最好！",
      朵朵: "朵朵姐姐……（脸红）",
      朵朵妈: "阿姨好凶……",
    },
    schedule: "全天泡沙坑，偶尔被爷爷拎到凉亭。",
  },
  {
    id: "wang_ayi",
    name: "王阿姨",
    age: 55,
    emoji: "👵",
    homeId: "bench",
    color: "#c46c8a",
    persona: "小区八卦中心，退休没事干。每天在长椅区坐镇，谁家娃娃几岁、谁家老人病了她都门儿清。爱问年轻人「啥时候要二胎」。",
    voice: "嗓门大「哎呀」「你听说没」「我跟你讲」、爱问八卦。",
    relationships: {
      朵朵妈: "这小媳妇就是太紧张，我得多劝劝。",
      豆豆爷爷: "老豆头爱讲大道理。",
      朵朵: "朵朵这小姑娘真乖。",
      健身爷爷: "老张头一个人挺孤独。",
    },
    schedule: "全天在长椅区，扎堆其他大妈，傍晚才回家。",
  },
  {
    id: "fitness_grandpa",
    name: "老张头",
    age: 72,
    emoji: "🧓",
    homeId: "fitness",
    color: "#6c7a5c",
    persona: "独居老人，每天来健身角锻炼。话不多但礼貌、习惯一个人。其实希望有人聊聊，但又不主动。",
    voice: "「嗯」「您好」「锻炼锻炼」、说话简短。",
    relationships: {
      豆豆爷爷: "老豆话多但人不坏。",
      王阿姨: "王嫂子热心。",
      朵朵妈: "年轻人不容易。",
    },
    schedule: "上午健身角扭腰、下午长椅区看孩子玩，傍晚独自走回家。",
  },
];

export const playgroundScenario: Scenario = {
  id: "playground",
  name: "小区遛娃",
  description: "都市小区一角的常态：妈妈遛娃、爷爷宠孙、大妈八卦、独居老人独自锻炼。",
  world: {
    width: 32,
    height: 20,
    startHour: 8,
    tickMinutes: 5,
    timeOfDayHints: {
      "0-6": "凌晨，小区静悄悄。",
      "6-9": "清晨，老人来锻炼。",
      "9-11": "上午遛娃高峰，妈妈和爷爷奶奶都在。",
      "11-14": "中午回家吃饭，公共区域人少。",
      "14-17": "下午继续遛娃，老人扎堆。",
      "17-19": "傍晚最热闹，下班的家长也加入。",
      "19-22": "晚饭后散步，大爷大妈遛弯。",
      "22-24": "夜深，小区安静。",
    },
  },
  places: PLACES,
  characters: CHARACTERS,
};
